### ISSUE TITLE
Notes of Linear Algebra

### ISSUE THREAD

**Issue by Jash-Shah** [vrnimje/Inverted-LQR-Bot-Eklavya#1]
Upload notes of [Linear Algebra Playlist](https://www.youtube.com/playlist?list=PL0-GT3co4r2y2YErbmuJw2L5tW4Ew2O5B). Can be in markdown or handwritten.

**Comment by vrnimje** [comment]
Added the notes here:
https://github.com/vrnimje/Inverted-LQR-Bot-Eklavya/tree/develop
