### ISSUE TITLE
Notes of Control Systems

### ISSUE THREAD

**Issue by Jash-Shah** [vrnimje/Inverted-LQR-Bot-Eklavya#2]
Upload notes on [Control Systems Bootcamp](https://www.youtube.com/playlist?list=PLMrJAkhIeNNR20Mz-VpzgfQs5zrYi085m). Can be in markdown or handwritten.

**Comment by vrnimje** [comment]
https://github.com/vrnimje/Inverted-LQR-Bot-Eklavya/blob/develop/Control_Bootcamp_Vedant.md
